import React, { useEffect, useState } from 'react'
import { assets } from '../../assets/assets'
import moment from 'moment'
import Markdown from 'react-markdown'
import Prism from 'prismjs'
import { useAppContext } from '../../context/AppContext'

const Message = ({ message, isPublic }) => {

  const { user } = useAppContext();

  const [imageLoaded, setImageLoaded] = useState(false);
  const [imageError, setImageError] = useState(false);

  useEffect(() => {

    if (message.isImage) {
      setImageLoaded(false);
      setImageError(false);
    }

  }, [message.isImage, message.content]);

  const handleImageLoad = () => {

    setImageLoaded(true);

  };

  const handleImageError = () => {

    setImageError(true);
    setImageLoaded(true);

  };

  useEffect(() => {

    //Here, prism is used to format the code content generated by the ai
    Prism.highlightAll();

  }, [message.content]);

  return (
    <div>

      {message.role === 'user' ?
        (
          <div className='flex items-start justify-end my-4 gap-2'>

            <div className='flex flex-col gap-2 p-2 px-4 bg-slate-50 dark:bg-[#57317c] border border-[#80609f]/30 rounded-md max-w-2xl'>

              <div className='text-sm dark:text-primary'><Markdown>{message.content}</Markdown></div>

              <span className='text-xs text-gray-400 dark:text-[#b1a6c0]'>{moment(message.timestamp).fromNow()}</span>

            </div>

            {isPublic ?
              (<img src={assets.user_icon} className='max-sm:hidden w-8 rounded-full' alt="" />)
              :
              (<img src={user?.imageUrl} className='max-sm:hidden w-8 rounded-full' alt="" />)
            }


          </div>
        )
        :
        (
          <div className='flex gap-2 items-start'>

            <img src={assets.logo} className='max-sm:hidden w-8 rounded-full my-4' alt="" />

            <div className='inline-flex flex-col gap-2 py-3 px-4 my-1 sm:my-4 bg-primary/20 dark:bg-[#57317c]/30 border border-[#80609f]/30 rounded-md max-w-2xl'>

              {message.isImage ?

                (

                  <div className="relative">

                    {/* Loading State */}
                    {!imageLoaded && !imageError && (
                      <div className="flex items-center justify-center w-50 h-50 lg:w-80 lg:h-80 bg-gray-200 dark:bg-gray-700 rounded-lg">

                        <div className="flex flex-col items-center gap-2">
                          <div className="flex gap-1">
                            <div className="w-2 h-2 bg-gray-500 rounded-full animate-bounce"></div>
                            <div className="w-2 h-2 bg-gray-500 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
                            <div className="w-2 h-2 bg-gray-500 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
                          </div>
                          <p className="text-xs text-gray-500">Loading image...</p>
                        </div>

                      </div>
                    )}

                    {/* Error State */}
                    {imageError && (
                      <div className="flex items-center justify-center lg:w-80 lg:h-80 bg-gray-200 dark:bg-gray-700 rounded-lg">
                        <div className="text-center">
                          <p className="text-sm text-gray-500">Failed to load image</p>
                          <button
                            onClick={() => {
                              setImageLoaded(false);
                              setImageError(false);
                            }}
                            className="mt-2 text-xs text-blue-500 hover:text-blue-600"
                          >
                            Retry
                          </button>
                        </div>
                      </div>
                    )}

                    <img
                      src={message.content}
                      alt="Generated AI image"
                      className={`lg:w-80 lg:h-80 mt-3 object-cover rounded-lg transition-opacity duration-300 ${imageLoaded ? 'opacity-100' : 'opacity-0'
                        }`}
                      onLoad={handleImageLoad}
                      onError={handleImageError}
                      style={{ display: imageLoaded ? 'block' : 'none' }}
                    />

                  </div>
                )
                :
                (
                  <div className='text-sm dark:text-primary reset-tw'>
                    <Markdown>{message.content}</Markdown>
                  </div>
                )

              }

              <span className='text-xs text-gray-400 dark:text-[#b1a6c0]'>{moment(message.timestamp).fromNow()}</span>

            </div>

          </div>
        )
      }

    </div>
  )
}

export default Message