import React, { useEffect } from 'react'
import { assets } from '../assets/assets'
import moment from 'moment'
import Markdown from 'react-markdown'
import Prism from 'prismjs'
import { useAppContext } from '../context/AppContext'

const Message = ({ message }) => {

  const {user} = useAppContext();

  useEffect(()=>{

    //Here, prism is used to format the code content generated by the ai
    Prism.highlightAll();

  }, [message.content]); 

  return (
    <div>

      {message.role === 'user' ?
        (
          <div className='flex items-start justify-end my-4 gap-2'>

            <div className='flex flex-col gap-2 p-2 px-4 bg-slate-50 dark:bg-[#57317c] border border-[#80609f]/30 rounded-md max-w-2xl'>

              <p className='text-sm dark:text-primary'>{message.content}</p>

              <span className='text-xs text-gray-400 dark:text-[#b1a6c0]'>{moment(message.timestamp).fromNow()}</span>

            </div>

            <img src={user.imageUrl} className='w-8 rounded-full' alt="" />

          </div>
        )
        :
        (
          <div className='flex gap-2 items-start'>

            <img src={assets.logo} className='w-8 rounded-full  my-4' alt="" />

            <div className='inline-flex flex-col gap-2 p-2 px-4 my-4 bg-primary/20 dark:bg-[#57317c]/30 border border-[#80609f]/30 rounded-md max-w-2xl'>

              {message.isImage ?

                (
                  <img src={message.content} className='w-full max-w-md mt-2 rounded-md' alt="" />
                )
                :
                (
                  <div className='text-sm dark:text-primary reset-tw'>
                    <Markdown>{message.content}</Markdown>
                  </div>
                )

              }

              <span className='text-xs text-gray-400 dark:text-[#b1a6c0]'>{moment(message.timestamp).fromNow()}</span>

            </div>

          </div>
        )
      }

    </div>
  )
}

export default Message